name: 테카르타의 블로그
author: Tekhartha
baseurl: /herring-cove
description: theme for jekyll
github: http://www.github.com/dha8102
facebook: https://www.facebook.com/dha8102
email: dha8102@naver.com
disqus: diqus-dha8102

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
